[package]
name = "solamp_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anchor-lang = "0.31.1"
solana-client = "2.0.25"
solana-sdk = "2.0.25"
borsh = "0.10"
blake3 = "1.5"
serde = { version = "1.0", features = ["derive"] }
libc = "0.2"
